name: Worldstats
version: ${project.version}
main: me.moomoo.worldstats.Main
softdepend: [PlaceholderAPI]
commands:
  worldstats:
    usage: /<command>
    description: stats
    aliases: [/worldstats, /info, /stats]